export default {
    "de": {
        "accepted": "{attribute} muss akzeptiert werden.",
        "active_url": "{attribute} ist keine gültige Internet-Adresse.",
        "after": "{attribute} muss ein Datum nach dem {date} sein.",
        "after_or_equal": "{attribute} muss ein Datum nach dem {date} oder gleich dem {date} sein.",
        "alpha": "{attribute} darf nur aus Buchstaben bestehen.",
        "alpha_dash": "{attribute} darf nur aus Buchstaben, Zahlen, Binde- und Unterstrichen bestehen.",
        "alpha_num": "{attribute} darf nur aus Buchstaben und Zahlen bestehen.",
        "array": "{attribute} muss ein Array sein.",
        "before": "{attribute} muss ein Datum vor dem {date} sein.",
        "before_or_equal": "{attribute} muss ein Datum vor dem {date} oder gleich dem {date} sein.",
        "between": {
            "numeric": "{attribute} muss zwischen {min} & {max} liegen.",
            "file": "{attribute} muss zwischen {min} & {max} Kilobytes groß sein.",
            "string": "{attribute} muss zwischen {min} & {max} Zeichen lang sein.",
            "array": "{attribute} muss zwischen {min} & {max} Elemente haben."
        },
        "boolean": "{attribute} muss entweder 'true' oder 'false' sein.",
        "confirmed": "{attribute} stimmt nicht mit der Bestätigung überein.",
        "date": "{attribute} muss ein gültiges Datum sein.",
        "date_equals": "The {attribute} must be a date equal to {date}.",
        "date_format": "{attribute} entspricht nicht dem gültigen Format für {format}.",
        "different": "{attribute} und {other} müssen sich unterscheiden.",
        "digits": "{attribute} muss {digits} Stellen haben.",
        "digits_between": "{attribute} muss zwischen {min} und {max} Stellen haben.",
        "dimensions": "{attribute} hat ungültige Bildabmessungen.",
        "distinct": "{attribute} beinhaltet einen bereits vorhandenen Wert.",
        "email": "{attribute} muss eine gültige E-Mail-Adresse sein.",
        "exists": "Der gewählte Wert für {attribute} ist ungültig.",
        "file": "{attribute} muss eine Datei sein.",
        "filled": "{attribute} muss ausgefüllt sein.",
        "gt": {
            "numeric": "{attribute} muss mindestens {value} sein.",
            "file": "{attribute} muss mindestens {value} Kilobytes groß sein.",
            "string": "{attribute} muss mindestens {value} Zeichen lang sein.",
            "array": "{attribute} muss mindestens {value} Elemente haben."
        },
        "gte": {
            "numeric": "{attribute} muss größer oder gleich {value} sein.",
            "file": "{attribute} muss größer oder gleich {value} Kilobytes sein.",
            "string": "{attribute} muss größer oder gleich {value} Zeichen lang sein.",
            "array": "{attribute} muss größer oder gleich {value} Elemente haben."
        },
        "image": "{attribute} muss ein Bild sein.",
        "in": "Der gewählte Wert für {attribute} ist ungültig.",
        "in_array": "Der gewählte Wert für {attribute} kommt nicht in {other} vor.",
        "integer": "{attribute} muss eine ganze Zahl sein.",
        "ip": "{attribute} muss eine gültige IP-Adresse sein.",
        "ipv4": "{attribute} muss eine gültige IPv4-Adresse sein.",
        "ipv6": "{attribute} muss eine gültige IPv6-Adresse sein.",
        "json": "{attribute} muss ein gültiger JSON-String sein.",
        "lt": {
            "numeric": "{attribute} muss kleiner {value} sein.",
            "file": "{attribute} muss kleiner {value} Kilobytes groß sein.",
            "string": "{attribute} muss kleiner {value} Zeichen lang sein.",
            "array": "{attribute} muss kleiner {value} Elemente haben."
        },
        "lte": {
            "numeric": "{attribute} muss kleiner oder gleich {value} sein.",
            "file": "{attribute} muss kleiner oder gleich {value} Kilobytes sein.",
            "string": "{attribute} muss kleiner oder gleich {value} Zeichen lang sein.",
            "array": "{attribute} muss kleiner oder gleich {value} Elemente haben."
        },
        "max": {
            "numeric": "{attribute} darf maximal {max} sein.",
            "file": "{attribute} darf maximal {max} Kilobytes groß sein.",
            "string": "{attribute} darf maximal {max} Zeichen haben.",
            "array": "{attribute} darf nicht mehr als {max} Elemente haben."
        },
        "mimes": "{attribute} muss den Dateityp {values} haben.",
        "mimetypes": "{attribute} muss den Dateityp {values} haben.",
        "min": {
            "numeric": "{attribute} muss mindestens {min} sein.",
            "file": "{attribute} muss mindestens {min} Kilobytes groß sein.",
            "string": "{attribute} muss mindestens {min} Zeichen lang sein.",
            "array": "{attribute} muss mindestens {min} Elemente haben."
        },
        "not_in": "Der gewählte Wert für {attribute} ist ungültig.",
        "not_regex": "{attribute} hat ein ungültiges Format.",
        "numeric": "{attribute} muss eine Zahl sein.",
        "present": "{attribute} muss vorhanden sein.",
        "regex": "{attribute} Format ist ungültig.",
        "required": "{attribute} muss ausgefüllt sein.",
        "required_if": "{attribute} muss ausgefüllt sein, wenn {other} {value} ist.",
        "required_unless": "{attribute} muss ausgefüllt sein, wenn {other} nicht {values} ist.",
        "required_with": "{attribute} muss angegeben werden, wenn {values} ausgefüllt wurde.",
        "required_with_all": "{attribute} muss angegeben werden, wenn {values} ausgefüllt wurde.",
        "required_without": "{attribute} muss angegeben werden, wenn {values} nicht ausgefüllt wurde.",
        "required_without_all": "{attribute} muss angegeben werden, wenn keines der Felder {values} ausgefüllt wurde.",
        "same": "{attribute} und {other} müssen übereinstimmen.",
        "size": {
            "numeric": "{attribute} muss gleich {size} sein.",
            "file": "{attribute} muss {size} Kilobyte groß sein.",
            "string": "{attribute} muss {size} Zeichen lang sein.",
            "array": "{attribute} muss genau {size} Elemente haben."
        },
        "starts_with": "The {attribute} must start with one of the following: {values}",
        "string": "{attribute} muss ein String sein.",
        "timezone": "{attribute} muss eine gültige Zeitzone sein.",
        "unique": "{attribute} ist schon vergeben.",
        "uploaded": "{attribute} konnte nicht hochgeladen werden.",
        "url": "{attribute} muss eine URL sein.",
        "uuid": "{attribute} muss ein UUID sein.",
        "custom": {
            "attribute-name": {
                "rule-name": "custom-message"
            }
        },
        "attributes": {
            "name": "Name",
            "username": "Benutzername",
            "email": "E-Mail-Adresse",
            "first_name": "Vorname",
            "last_name": "Nachname",
            "password": "Passwort",
            "password_confirmation": "Passwort-Bestätigung",
            "city": "Stadt",
            "country": "Land",
            "address": "Adresse",
            "phone": "Telefonnummer",
            "mobile": "Handynummer",
            "age": "Alter",
            "sex": "Geschlecht",
            "gender": "Geschlecht",
            "day": "Tag",
            "month": "Monat",
            "year": "Jahr",
            "hour": "Stunde",
            "minute": "Minute",
            "second": "Sekunde",
            "title": "Titel",
            "content": "Inhalt",
            "description": "Beschreibung",
            "excerpt": "Auszug",
            "date": "Datum",
            "time": "Uhrzeit",
            "available": "verfügbar",
            "size": "Größe"
        }
    },
    "en": {
        "accepted": "The {attribute} must be accepted.",
        "active_url": "The {attribute} is not a valid URL.",
        "after": "The {attribute} must be a date after {date}.",
        "after_or_equal": "The {attribute} must be a date after or equal to {date}.",
        "alpha": "The {attribute} must only contain letters.",
        "alpha_dash": "The {attribute} must only contain letters, numbers, dashes and underscores.",
        "alpha_num": "The {attribute} must only contain letters and numbers.",
        "array": "The {attribute} must be an array.",
        "before": "The {attribute} must be a date before {date}.",
        "before_or_equal": "The {attribute} must be a date before or equal to {date}.",
        "between": {
            "numeric": "The {attribute} must be between {min} and {max}.",
            "file": "The {attribute} must be between {min} and {max} kilobytes.",
            "string": "The {attribute} must be between {min} and {max} characters.",
            "array": "The {attribute} must have between {min} and {max} items."
        },
        "boolean": "The {attribute} field must be true or false.",
        "confirmed": "The {attribute} confirmation does not match.",
        "date": "The {attribute} is not a valid date.",
        "date_equals": "The {attribute} must be a date equal to {date}.",
        "date_format": "The {attribute} does not match the format {format}.",
        "different": "The {attribute} and {other} must be different.",
        "digits": "The {attribute} must be {digits} digits.",
        "digits_between": "The {attribute} must be between {min} and {max} digits.",
        "dimensions": "The {attribute} has invalid image dimensions.",
        "distinct": "The {attribute} field has a duplicate value.",
        "email": "The {attribute} must be a valid email address.",
        "ends_with": "The {attribute} must end with one of the following: {values}.",
        "exists": "The selected {attribute} is invalid.",
        "file": "The {attribute} must be a file.",
        "filled": "The {attribute} field must have a value.",
        "gt": {
            "numeric": "The {attribute} must be greater than {value}.",
            "file": "The {attribute} must be greater than {value} kilobytes.",
            "string": "The {attribute} must be greater than {value} characters.",
            "array": "The {attribute} must have more than {value} items."
        },
        "gte": {
            "numeric": "The {attribute} must be greater than or equal {value}.",
            "file": "The {attribute} must be greater than or equal {value} kilobytes.",
            "string": "The {attribute} must be greater than or equal {value} characters.",
            "array": "The {attribute} must have {value} items or more."
        },
        "image": "The {attribute} must be an image.",
        "in": "The selected {attribute} is invalid.",
        "in_array": "The {attribute} field does not exist in {other}.",
        "integer": "The {attribute} must be an integer.",
        "ip": "The {attribute} must be a valid IP address.",
        "ipv4": "The {attribute} must be a valid IPv4 address.",
        "ipv6": "The {attribute} must be a valid IPv6 address.",
        "json": "The {attribute} must be a valid JSON string.",
        "lt": {
            "numeric": "The {attribute} must be less than {value}.",
            "file": "The {attribute} must be less than {value} kilobytes.",
            "string": "The {attribute} must be less than {value} characters.",
            "array": "The {attribute} must have less than {value} items."
        },
        "lte": {
            "numeric": "The {attribute} must be less than or equal {value}.",
            "file": "The {attribute} must be less than or equal {value} kilobytes.",
            "string": "The {attribute} must be less than or equal {value} characters.",
            "array": "The {attribute} must not have more than {value} items."
        },
        "max": {
            "numeric": "The {attribute} must not be greater than {max}.",
            "file": "The {attribute} must not be greater than {max} kilobytes.",
            "string": "The {attribute} must not be greater than {max} characters.",
            "array": "The {attribute} must not have more than {max} items."
        },
        "mimes": "The {attribute} must be a file of type: {values}.",
        "mimetypes": "The {attribute} must be a file of type: {values}.",
        "min": {
            "numeric": "The {attribute} must be at least {min}.",
            "file": "The {attribute} must be at least {min} kilobytes.",
            "string": "The {attribute} must be at least {min} characters.",
            "array": "The {attribute} must have at least {min} items."
        },
        "multiple_of": "The {attribute} must be a multiple of {value}.",
        "not_in": "The selected {attribute} is invalid.",
        "not_regex": "The {attribute} format is invalid.",
        "numeric": "The {attribute} must be a number.",
        "password": "The password is incorrect.",
        "present": "The {attribute} field must be present.",
        "regex": "The {attribute} format is invalid.",
        "required": "The {attribute} field is required.",
        "required_if": "The {attribute} field is required when {other} is {value}.",
        "required_unless": "The {attribute} field is required unless {other} is in {values}.",
        "required_with": "The {attribute} field is required when {values} is present.",
        "required_with_all": "The {attribute} field is required when {values} are present.",
        "required_without": "The {attribute} field is required when {values} is not present.",
        "required_without_all": "The {attribute} field is required when none of {values} are present.",
        "prohibited": "The {attribute} field is prohibited.",
        "prohibited_if": "The {attribute} field is prohibited when {other} is {value}.",
        "prohibited_unless": "The {attribute} field is prohibited unless {other} is in {values}.",
        "same": "The {attribute} and {other} must match.",
        "size": {
            "numeric": "The {attribute} must be {size}.",
            "file": "The {attribute} must be {size} kilobytes.",
            "string": "The {attribute} must be {size} characters.",
            "array": "The {attribute} must contain {size} items."
        },
        "starts_with": "The {attribute} must start with one of the following: {values}.",
        "string": "The {attribute} must be a string.",
        "timezone": "The {attribute} must be a valid zone.",
        "unique": "The {attribute} has already been taken.",
        "uploaded": "The {attribute} failed to upload.",
        "url": "The {attribute} format is invalid.",
        "uuid": "The {attribute} must be a valid UUID.",
        "custom": {
            "attribute-name": {
                "rule-name": "custom-message"
            }
        },
        "attributes": []
    },
    "fr": {
        "accepted": "Le champ {attribute} doit être accepté.",
        "active_url": "Le champ {attribute} n'est pas une URL valide.",
        "after": "Le champ {attribute} doit être une date postérieure au {date}.",
        "after_or_equal": "Le champ {attribute} doit être une date postérieure ou égale au {date}.",
        "alpha": "Le champ {attribute} doit contenir uniquement des lettres.",
        "alpha_dash": "Le champ {attribute} doit contenir uniquement des lettres, des chiffres et des tirets.",
        "alpha_num": "Le champ {attribute} doit contenir uniquement des chiffres et des lettres.",
        "array": "Le champ {attribute} doit être un tableau.",
        "before": "Le champ {attribute} doit être une date antérieure au {date}.",
        "before_or_equal": "Le champ {attribute} doit être une date antérieure ou égale au {date}.",
        "between": {
            "numeric": "La valeur de {attribute} doit être comprise entre {min} et {max}.",
            "file": "La taille du fichier de {attribute} doit être comprise entre {min} et {max} kilo-octets.",
            "string": "Le texte {attribute} doit contenir entre {min} et {max} caractères.",
            "array": "Le tableau {attribute} doit contenir entre {min} et {max} éléments."
        },
        "boolean": "Le champ {attribute} doit être vrai ou faux.",
        "confirmed": "Le champ de confirmation {attribute} ne correspond pas.",
        "date": "Le champ {attribute} n'est pas une date valide.",
        "date_equals": "Le champ {attribute} doit être une date égale à {date}.",
        "date_format": "Le champ {attribute} ne correspond pas au format {format}.",
        "different": "Les champs {attribute} et {other} doivent être différents.",
        "digits": "Le champ {attribute} doit contenir {digits} chiffres.",
        "digits_between": "Le champ {attribute} doit contenir entre {min} et {max} chiffres.",
        "dimensions": "La taille de l'image {attribute} n'est pas conforme.",
        "distinct": "Le champ {attribute} a une valeur en double.",
        "email": "Le champ {attribute} doit être une adresse email valide.",
        "exists": "Le champ {attribute} sélectionné est invalide.",
        "file": "Le champ {attribute} doit être un fichier.",
        "filled": "Le champ {attribute} doit avoir une valeur.",
        "gt": {
            "numeric": "La valeur de {attribute} doit être supérieure à {value}.",
            "file": "La taille du fichier de {attribute} doit être supérieure à {value} kilo-octets.",
            "string": "Le texte {attribute} doit contenir plus de {value} caractères.",
            "array": "Le tableau {attribute} doit contenir plus de {value} éléments."
        },
        "gte": {
            "numeric": "La valeur de {attribute} doit être supérieure ou égale à {value}.",
            "file": "La taille du fichier de {attribute} doit être supérieure ou égale à {value} kilo-octets.",
            "string": "Le texte {attribute} doit contenir au moins {value} caractères.",
            "array": "Le tableau {attribute} doit contenir au moins {value} éléments."
        },
        "image": "Le champ {attribute} doit être une image.",
        "in": "Le champ {attribute} est invalide.",
        "in_array": "Le champ {attribute} n'existe pas dans {other}.",
        "integer": "Le champ {attribute} doit être un entier.",
        "ip": "Le champ {attribute} doit être une adresse IP valide.",
        "ipv4": "Le champ {attribute} doit être une adresse IPv4 valide.",
        "ipv6": "Le champ {attribute} doit être une adresse IPv6 valide.",
        "json": "Le champ {attribute} doit être un document JSON valide.",
        "lt": {
            "numeric": "La valeur de {attribute} doit être inférieure à {value}.",
            "file": "La taille du fichier de {attribute} doit être inférieure à {value} kilo-octets.",
            "string": "Le texte {attribute} doit contenir moins de {value} caractères.",
            "array": "Le tableau {attribute} doit contenir moins de {value} éléments."
        },
        "lte": {
            "numeric": "La valeur de {attribute} doit être inférieure ou égale à {value}.",
            "file": "La taille du fichier de {attribute} doit être inférieure ou égale à {value} kilo-octets.",
            "string": "Le texte {attribute} doit contenir au plus {value} caractères.",
            "array": "Le tableau {attribute} doit contenir au plus {value} éléments."
        },
        "max": {
            "numeric": "La valeur de {attribute} ne peut être supérieure à {max}.",
            "file": "La taille du fichier de {attribute} ne peut pas dépasser {max} kilo-octets.",
            "string": "Le texte de {attribute} ne peut contenir plus de {max} caractères.",
            "array": "Le tableau {attribute} ne peut contenir plus de {max} éléments."
        },
        "mimes": "Le champ {attribute} doit être un fichier de type : {values}.",
        "mimetypes": "Le champ {attribute} doit être un fichier de type : {values}.",
        "min": {
            "numeric": "La valeur de {attribute} doit être supérieure ou égale à {min}.",
            "file": "La taille du fichier de {attribute} doit être supérieure à {min} kilo-octets.",
            "string": "Le texte {attribute} doit contenir au moins {min} caractères.",
            "array": "Le tableau {attribute} doit contenir au moins {min} éléments."
        },
        "not_in": "Le champ {attribute} sélectionné n'est pas valide.",
        "not_regex": "Le format du champ {attribute} n'est pas valide.",
        "numeric": "Le champ {attribute} doit contenir un nombre.",
        "present": "Le champ {attribute} doit être présent.",
        "regex": "Le format du champ {attribute} est invalide.",
        "required": "Le champ {attribute} est obligatoire.",
        "required_if": "Le champ {attribute} est obligatoire quand la valeur de {other} est {value}.",
        "required_unless": "Le champ {attribute} est obligatoire sauf si {other} est {values}.",
        "required_with": "Le champ {attribute} est obligatoire quand {values} est présent.",
        "required_with_all": "Le champ {attribute} est obligatoire quand {values} sont présents.",
        "required_without": "Le champ {attribute} est obligatoire quand {values} n'est pas présent.",
        "required_without_all": "Le champ {attribute} est requis quand aucun de {values} n'est présent.",
        "same": "Les champs {attribute} et {other} doivent être identiques.",
        "size": {
            "numeric": "La valeur de {attribute} doit être {size}.",
            "file": "La taille du fichier de {attribute} doit être de {size} kilo-octets.",
            "string": "Le texte de {attribute} doit contenir {size} caractères.",
            "array": "Le tableau {attribute} doit contenir {size} éléments."
        },
        "starts_with": "Le champ {attribute} doit commencer avec une des valeurs suivantes : {values}",
        "string": "Le champ {attribute} doit être une chaîne de caractères.",
        "timezone": "Le champ {attribute} doit être un fuseau horaire valide.",
        "unique": "La valeur du champ {attribute} est déjà utilisée.",
        "uploaded": "Le fichier du champ {attribute} n'a pu être téléversé.",
        "url": "Le format de l'URL de {attribute} n'est pas valide.",
        "uuid": "Le champ {attribute} doit être un UUID valide",
        "custom": {
            "attribute-name": {
                "rule-name": "custom-message"
            }
        },
        "attributes": {
            "name": "nom",
            "username": "nom d'utilisateur",
            "email": "adresse email",
            "first_name": "prénom",
            "last_name": "nom",
            "password": "mot de passe",
            "password_confirmation": "confirmation du mot de passe",
            "city": "ville",
            "country": "pays",
            "address": "adresse",
            "phone": "téléphone",
            "mobile": "portable",
            "age": "âge",
            "sex": "sexe",
            "gender": "genre",
            "day": "jour",
            "month": "mois",
            "year": "année",
            "hour": "heure",
            "minute": "minute",
            "second": "seconde",
            "title": "titre",
            "content": "contenu",
            "description": "description",
            "excerpt": "extrait",
            "date": "date",
            "time": "heure",
            "available": "disponible",
            "size": "taille"
        }
    }
}
